version: 2

models:
  - name: dm_perfomance_product_by_province
    description: "Performance sales product by province"
    columns:
      - name: province_name
        description: "Name of the province"
        tests:
          - not_null
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: total_quantity
        description: "Total quantity of product"
        tests:
          - not_null
      - name: total_sales
        description: "Total sales of the product"
        tests:
          - not_null

  - name: dm_revenue_by_months
    description: "Revenue by month"
    columns:
      - name: month
        description: "Month of revenue"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue per month"
        tests:
          - not_null