version: 2

models:
  - name: dim_customer
    description: This table has basic information about a customer
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name. 
        tests:
          - not_null
      - name: last_name
        description: Customer's last name. 
        tests:
          - not_null
      - name: gender
        description: gender of customer's
        tests:
          - not_null


  - name: dim_location
    description: This table has basic information location of city and provice
    columns:
      - name: city_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for a city
      - name: city_names
        tests:
          - not_null
      - name: province_id
        description: This is a unique identifier for a province
        tests:
            - unique
            - not_null
      - name: province_name
        tests:
            - not_null

  - name: dim_products
    description: This table has basic information about a products
    columns:
      - name: product_id
        description: This is a unique identifier for a products
        tests:
          - unique
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: size
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: product_category_id
        description: This is a unique identifier for a products category
        tests:
          - unique
          - not_null     
      - name: product_category_name
        tests:
          - unique
          - not_null

